services:
  # IMAGE GENERATOR
  image-api:
    build:
      context: ./image-generator
      dockerfile: Dockerfile.api
    env_file:
      - .env
    ports:
      - "8001:8000"
    depends_on:
      - image-redis
    networks:
      - fal_ai_image-net
    restart: always
    deploy:
      resources:
        limits:
          memory: 400M
          cpus: '0.25'
    

  image-worker:
    build:
      context: ./image-generator
      dockerfile: Dockerfile.worker
    env_file:
      - .env
    depends_on:
      - image-redis
    networks:
      - fal_ai_image-net
    restart: always
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.2'

  image-redis:
    image: redis:latest
    ports:
      - "6371:6379"
    networks:
      - fal_ai_image-net
    restart: always
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.15'




  # VIDEO GENERATOR
  video-api:
    build:
      context: ./video-generator
      dockerfile: Dockerfile.api
    env_file:
      - .env
    ports:
      - "8002:8000"
    depends_on:
      - video-redis
    networks:
      - fal_ai_video-net
    restart: always
    deploy:
      resources:
        limits:
          memory: 400M
          cpus: '0.25'

  video-worker:
    build:
      context: ./video-generator
      dockerfile: Dockerfile.worker
    env_file:
      - .env
    depends_on:
      - video-redis
    networks:
      - fal_ai_video-net
    restart: always
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.2'

  video-redis:
    image: redis:latest
    ports:
      - "6372:6379"
    networks:
      - fal_ai_video-net
    restart: always
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.15'





  # VIDEO TO VIDEO
  video2video-api:
    build:
      context: ./video-to-video
      dockerfile: Dockerfile.api
    env_file:
      - .env
    ports:
      - "8003:8000"
    depends_on:
      - video2video-redis
    networks:
      - fal_ai_video2video-net
    restart: always
    deploy:
      resources:
        limits:
          memory: 400M
          cpus: '0.25'

  video2video-worker:
    build:
      context: ./video-to-video
      dockerfile: Dockerfile.worker
    env_file:
      - .env
    depends_on:
      - video2video-redis
    networks:
      - fal_ai_video2video-net
    restart: always
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.2'

  video2video-redis:
    image: redis:latest
    ports:
      - "6373:6379"
    networks:
      - fal_ai_video2video-net
    restart: always
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.15'




  # IMAGE TRAINING
  train-images-api:
    build:
      context: ./train-images
      dockerfile: Dockerfile.api
    env_file:
      - .env
    ports:
      - "8004:8000"
    depends_on:
      - train-images-redis
    networks:
      - fal_ai_train-images-net
    restart: always
    deploy:
      resources:
        limits:
          memory: 400M
          cpus: '0.25'

  train-images-worker:
    build:
      context: ./train-images
      dockerfile: Dockerfile.worker
    env_file:
      - .env
    depends_on:
      - train-images-redis
    networks:
      - fal_ai_train-images-net
    restart: always
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.2'

  train-images-redis:
    image: redis:latest
    ports:
      - "6374:6379"
    networks:
      - fal_ai_train-images-net
    restart: always
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.15'





  # IMAGE PROCESSING
  image-processing-api:
    build:
      context: ./image-processing
      dockerfile: Dockerfile.api
    env_file:
      - .env
    ports:
      - "8005:8000"
    depends_on:
      - image-processing-redis
    networks:
      - fal_ai_image-processing-net
    restart: always
    deploy:
      resources:
        limits:
          memory: 400M
          cpus: '0.25'

  image-processing-worker:
    build:
      context: ./image-processing
      dockerfile: Dockerfile.worker
    env_file:
      - .env
    depends_on:
      - image-processing-redis
    networks:
      - fal_ai_image-processing-net
    restart: always
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.2'

  image-processing-redis:
    image: redis:latest
    ports:
      - "6375:6379"
    networks:
      - fal_ai_image-processing-net
    restart: always
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.15'

networks:
  fal_ai_image-net:
    driver: bridge
  fal_ai_video-net:
    driver: bridge
  fal_ai_video2video-net:
    driver: bridge
  fal_ai_train-images-net:
    driver: bridge
  fal_ai_image-processing-net:
    driver: bridge
