version: "3.9"

services:
  #  API
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: "${TASK_TYPE}-api"
    env_file:
      - .env
    ports:
      - "${API_PORT}:8000"
    depends_on:
      - redis
    networks:
      - net
    restart: always

  #  Worker
  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: "${TASK_TYPE}-worker"
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - net
    deploy:
      replicas: ${WORKER_REPLICAS}
    restart: always

  # Redis
  redis:
    image: redis:latest
    container_name: "${TASK_TYPE}-redis"
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - net
    restart: always

networks:
  net:
