version: "3.9"

services:
  # IMAGE GENERATOR
  image-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    env_file:
      - .env
    ports:
      - "8001:8000"
    depends_on:
      - image-redis
    networks:
      - image-net
    restart: always

  image-worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    env_file:
      - .env
    depends_on:
      - image-redis
    networks:
      - image-net
    deploy:
      replicas: 5
    restart: always

  image-redis:
    image: redis:latest
    ports:
      - "6371:6379"
    networks:
      - image-net
    restart: always

  # VIDEO GENERATOR
  video-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    env_file:
      - .env
    ports:
      - "8002:8000"
    depends_on:
      - video-redis
    networks:
      - video-net
    restart: always

  video-worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    env_file:
      - .env
    depends_on:
      - video-redis
    networks:
      - video-net
    deploy:
      replicas: 5
    restart: always

  video-redis:
    image: redis:latest
    ports:
      - "6372:6379"
    networks:
      - video-net
    restart: always

  # VIDEO TO VIDEO
  video2video-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    env_file:
      - .env
    ports:
      - "8003:8000"
    depends_on:
      - video2video-redis
    networks:
      - video2video-net
    restart: always

  v2v-worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    env_file:
      - .env
    depends_on:
      - video2video-redis
    networks:
      - video2video-net
    deploy:
      replicas: 5
    restart: always

  video2video-redis:
    image: redis:latest
    ports:
      - "6373:6379"
    networks:
      - video2video-net
    restart: always

  # IMAGE TRAINING
  train-images-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    env_file:
      - .env
    ports:
      - "8004:8000"
    depends_on:
      - train-images-redis
    networks:
      - train-images-net
    restart: always

  train-images-worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    env_file:
      - .env
    depends_on:
      - train-images-redis
    networks:
      - train-images-net
    deploy:
      replicas: 5
    restart: always

  train-images-redis:
    image: redis:latest
    ports:
      - "6374:6379"
    networks:
      - train-images-net
    restart: always

  # IMAGE PROCESSING
  image-processing-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    env_file:
      - .env
    ports:
      - "8005:8000"
    depends_on:
      - image-processing-redis
    networks:
      - image-processing-net
    restart: always

  image-processing-worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    env_file:
      - .env
    depends_on:
      - image-processing-redis
    networks:
      - image-processing-net
    deploy:
      replicas: 5
    restart: always

  image-processing-redis:
    image: redis:latest
    ports:
      - "6375:6379"
    networks:
      - image-processing-net
    restart: always

networks:
  image-net:
  video-net:
  video2video-net:
  train-images-net:
  image-processing-net:
