# Use Python image
FROM python:3.10

# Set working directory
WORKDIR /app

# Copy project files
COPY ./app /app
COPY requirements.txt /app/requirements.txt

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt


# Start Worker
CMD ["python", "worker.py"]
